### PR TITLE
TI-427: Add compatibility with Grape 2.2

### PR DESCRIPTION
**Pull request by zengraf**
Based on:
- https://github.com/ruby-grape/grape-swagger/pull/910
- https://github.com/ruby-grape/grape-swagger/pull/940

### CODE REVIEW

**Comment by maxemitchell** [comment]
Could you include the context around why we forked in the first place?

**Comment by dmoss18** [comment]
We could consider merging new changes from the origin branch instead of copy pasting them here

**Comment by zengraf** [comment]
@maxemitchell, I think it was done to add the functionality of hiding all endpoints by default, as it is not present in the original gem.

@dmoss18, sure, I opened the PR #11. I initially thought that there would be lots of conflicts, but there were not that many.

**Comment by zengraf** [comment]
Resolved with #11

**Pull request closed without merging**
